# Generated by Django 2.0.5 on 2018-06-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('situ', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor_total',
        ),
    ]
