# Generated by Django 2.0.5 on 2018-06-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20180619_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='id_mesa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='situ',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
