# Generated by Django 2.0.5 on 2018-05-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cargo', models.IntegerField()),
                ('senha', models.CharField(max_length=5)),
                ('cpf', models.CharField(max_length=12)),
                ('endereco', models.TextField(max_length=70)),
                ('telefone', models.CharField(max_length=12)),
            ],
        ),
    ]
