# Generated by Django 2.0.5 on 2018-06-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20180619_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='id_mesa',
        ),
    ]
